### PR TITLE
Changed first half of task to use resource table view

### PR DESCRIPTION
**Pull request by JulianJason**
Hello

Kindly double check on the changes
I am not too sure on how to use the resource table for the task-> sessions

### CODE REVIEW

**Comment by JulianJason** [comment]
Let me fix the error

**Comment by AndrewFeeney** [comment]
@JulianJason I haven't opened it in a browser yet, but the code looks fine. I should have been clearer about what to do with the sessions table for now, but I think you've more or less done what I would have expected. If you can fix the failing test, I'll check it again and merge it. Thanks!

**Comment by JulianJason** [comment]
@WebSpanner I'm sorry for the delay, I was working on another project.
I noticed it was just a small syntax error. This should work.

**Comment by AndrewFeeney** [comment]
Thanks @JulianJason

**Pull request merged**
